######################################################################
##
## Filename: user_logic.udo
## Created on: Thu Feb 09 4:26:51 PM Central Standard Time 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
